// importing react to use the components based architecture and needed to interpret JSX and in React 17 not needed.
import React, { useState } from "react";
// import "./CreateJobPosting.css"; // Import the CSS file

//PopUpToastContext is used to notify student when HR creates a JOB posting
import { usePopUpToastContext } from "../../context/PopUpToastContext";

// import Required for 3rd party Toast Notifications
import PopUpToast from "../../Global Components/PopUpToast/PopUpToast";

//Typescript interfaces
export interface JobData {
  //this is used in CompaniesList and JobCard components as well
  companyName: string;
  jobDescription: string;
  eligibility: string;
  applyLink: string;
  additionalDetails: string;
  timestamp: string;
  id?: string; //'id' is automatically generated by FireBase.So, it is optional
}

const CreateJobPosting: React.FC = () => {
  // const { handleJobAlert } = usePopUpToastContext();

  //State management
  // [variable , method to set the variable]
  // this state will store the companyname which is updated in the form and the method to set the companyname.
  const [companyName, setCompanyName] = useState<string>("");
  // this is the state which will store the jobDescription which is updated in the form and the method to set the companyname.
  const [jobDescription, setJobDescription] = useState<string>("");
  // the is the state which will store the eligibility criteria which is updated in the form and the method to set the companyname.
  const [eligibility, setEligibility] = useState<string>("");
  // this state will store the apply link which is updated in the form and the method to set the companyname.
  const [applyLink, setApplyLink] = useState<string>("");

  const [additionalDetails, setadditionalDetails] = useState<string>("");

  // When the form is submitted this method will be called.
  //this function may return nothin(ie.void) or it may return a promise(because of async)
  const handleSubmit = async (): Promise<void> => {
    try {
      if (companyName === "" || jobDescription === "" || applyLink === "") {
        PopUpToast.warning("Fill the required fields");
        return;
      }

      // Prepare the new job data
      const formData: JobData = {
        companyName,
        jobDescription,
        eligibility,
        applyLink,
        additionalDetails,
        timestamp: new Date().toISOString(), // Adds a timestamp in ISO format
      };

      const response = await fetch(
        "https://hrd-database-default-rtdb.asia-southeast1.firebasedatabase.app/jobs.json",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(formData),
        }
      );

      //here after posting the job,we dont know what response we would get from the server.
      //hence we are using Record(keys are strings and values are of any type)
      const data: Record<string, any> = await response.json();
      //Record<string,any> represents an object with string keys and any values.

      if (!response.ok) {
        throw new Error("Failed to add new job");
      }

      // Clear the form fields after successful submission
      setCompanyName("");
      setJobDescription("");
      setEligibility("");
      setApplyLink("");
      setadditionalDetails("");

      // Show a success toast message
      PopUpToast.success("Job posted successfully!");

      // Notify students
      // handleJobAlert();
    } catch (error) {
      // Handle errors
      console.error("Error posting data:", error);
      PopUpToast.warning(
        "There was an error submitting the form! Please check your server."
      );
    }
  };

  return (
    <form
      className="w-full max-w-xl mx-auto my-6 p-6 bg-gray-100 border border-gray-300 rounded-2xl shadow-md"
      onKeyDown={(e: React.KeyboardEvent<HTMLFormElement>) => {
        if (e.key === "Enter") {
          e.preventDefault();
          handleSubmit();
        }
      }}
    >
      <h2 className="text-center text-2xl font-semibold mb-6">
        Create Job Posting
      </h2>
      <div className="mb-4">
        <div className="flex gap-1 items-center">
          <label htmlFor="companyName" className="font-medium">
            Company Name
          </label>
          <span className="text-red-500"> *</span>
        </div>

        <input
          type="text"
          id="companyName"
          value={companyName}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
            setCompanyName(e.target.value);
          }}
          required
          className="w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-blue-400"
        />
      </div>
      <div className="mb-4">
        <div className="flex gap-1 items-center">
          <label htmlFor="jobDescription">Job Description</label>
          <span className="text-red-500"> *</span>
        </div>
        <textarea
          id="jobDescription"
          value={jobDescription}
          onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) =>
            setJobDescription(e.target.value)
          }
          required
          className="w-full p-3 border border-gray-300 rounded-md  resize-y focus:outline-none focus:ring-2 focus:ring-blue-400"
        />
      </div>
      <div className="mb-4">
        <div className="flex gap-1 items-center">
          <label htmlFor="eligibility" className="font-medium">
            Eligibility
          </label>
          <span className="text-red-500"> *</span>
        </div>
        <textarea
          id="eligibility"
          value={eligibility}
          onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) =>
            setEligibility(e.target.value)
          }
          required
          className="w-full p-3 border border-gray-300 rounded-md resize-y focus:outline-none focus:ring-2 focus:ring-blue-400"
        />
      </div>
      <div className="mb-4">
        <div className="flex gap-1 items-center">
          <label htmlFor="applyLink" className="font-medium">
            Apply Link
          </label>
          <span className="text-red-500"> *</span>
        </div>
        <input
          type="url"
          id="applyLink"
          value={applyLink}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
            setApplyLink(e.target.value)
          }
          required
          className="w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-blue-400"
        />
      </div>
      <div className="mb-4">
        <label htmlFor="additionalDetails" className="font-medium">
          Additional Details (Optional)
        </label>
        <textarea
          id="additionalDetails"
          value={additionalDetails}
          onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) =>
            setadditionalDetails(e.target.value)
          }
          className="w-full p-3 border border-gray-300 rounded-md resize-y focus:outline-none focus:ring-2 focus:ring-blue-400"
        />
      </div>
      <button
        className="w-full flex items-center justify-center bg-blue-600 text-white font-semibold py-3 rounded-full shadow-md transition hover:bg-blue-700"
        onClick={(e: React.MouseEvent<HTMLButtonElement>) => {
          e.preventDefault();
          handleSubmit();
        }}
      >
        Submit
      </button>
    </form>
  );
};

export default CreateJobPosting;
