//This Layout file is only for Landing and Login components.
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

//this should be included so as to get toast notifications through out the project.
import { ToastRootContainer } from "../components/PopUpToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* remember ToastRootContainer should be included in all layouts */}
        <ToastRootContainer></ToastRootContainer>
        <header className="bg-gradient-to-r from-blue-500 to-blue-500 py-5 text-center">
          <div className="max-w-2xl mx-auto">
            <h1 className="text-white font-bold text-4xl md:text-5xl">
              HRD-COHORT
            </h1>
            <p className="text-black-300 font-bold text-lg md:text-xl mt-5">
              Built for SJCIT-HRD Department
            </p>
          </div>
        </header>
        {children}
        <footer className="mt-auto text-center py-4 bg-blue-500 text-white text-sm">
          <p>&copy;2025 Cohort.All rights reserved</p>
        </footer>
      </body>
    </html>
  );
}
