import React, { useState, useEffect } from "react";
// import "./MessagingContainer.css";

import MessageDisplay from "../MessageDisplay/MessageDisplay";
import MessageInput from "../MessageInput/MessageInput";

// import Required for 3rd party Toast Notifications
import PopUpToast from "../../../Global Components/PopUpToast/PopUpToast";

//TS interfaces
export interface Message {
  date: string;
  sender: string;
  text: string;
  time: string;
  readonly id?: string; //this is automatically generated by FireBase . Hence its optional
}

const MessagingContainer: React.FC = () => {
  const [messages, setMessages] = useState<Message[]>([]);

  // Function to fetch messages from the JSON server
  const fetchMessages = async (): Promise<void> => {
    try {
      const response = await fetch(
        `https://hrd-database-default-rtdb.asia-southeast1.firebasedatabase.app/GroupMessages.json`,
        {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
          },
        }
      );

      if (!response.ok) {
        throw new Error(`Error fetching data: ${response.status}`);
      }

      const data: Message[] = await response.json(); // Fetch the data from JSONBin
      const messages = data || []; // Extract messages
      setMessages(messages); // Set messages in the state
    } catch (error) {
      console.error("Error fetching messages:", error);
    }
  };

  // Function to post a new message to the JSON server
  const postMessage = async (message: Message): Promise<void> => {
    try {
      // Step 1: Fetch the current GroupMessages object
      const response = await fetch(
        `https://hrd-database-default-rtdb.asia-southeast1.firebasedatabase.app/GroupMessages.json`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(message),
        }
      );

      if (!response.ok) {
        throw new Error(`Error fetching data: ${response.status}`);
      }

      fetchMessages(); //calling this function , so that latest message will be displayed
      PopUpToast.success("Message Sent Successfully!");
    } catch (error) {
      console.error("Error posting message:", error);
      PopUpToast.warning("There is some error while sending the message!");
    }
  };

  // Handle sending a message
  const handleSendMessage = (messageText: string): void => {
    // Get current date and time
    const now: Date = new Date();
    const formattedDate = now.toLocaleDateString(); // e.g., "11/02/2024"
    const formattedTime = now.toLocaleTimeString([], {
      hour: "2-digit",
      minute: "2-digit",
    }); // e.g., "12:45 PM"

    // Create the new message object with date and time
    const newMessage: Message = {
      sender: "HR",
      text: messageText,
      date: formattedDate,
      time: formattedTime,
    };

    postMessage(newMessage); // Call postMessage function to send it to the server
  };

  // Fetch messages when the component mounts
  useEffect(() => {
    fetchMessages();
  }, []);

  return (
    <div className="flex flex-col max-w-[70%] max-h-[90%] mx-auto mt-2 p-4 bg-white rounded-lg shadow-lg overflow-y-auto breakwords">
      <MessageDisplay />
      <MessageInput
        onSend={(messageText: string) => handleSendMessage(messageText)}
      />
    </div>
  );
};

export default MessagingContainer;
