"use client"; //this is a component , which contains client side logic(react hooks,event handlers..etc)

import { useState, useEffect, JSX } from "react";
//useState is used to store the email and password entered by user.And also it is used to store the password visibility status and credentials validity status.
//useEffect is used to reset the 'password' and 'email' attributes when the component is mounted.

//PopUpToast is used to display successful logins,invalid credentials..etc
import PopUpToastProvider from "../../../components/PopUpToastProvider";

import { useRouter, useSearchParams } from "next/navigation";
//useRouter hook is used to programmatically change routes inside client components.
//to get parameters from URL,we use {params}

//❌❌Export interfaces from this file to the entire application❌❌
//interface for registeredStudents and registeredHRs
export interface registeredStuds {
  USN: string;
  profileImg: string;
  website: string;
  name: string;
  email: string;
  password: string;
  mobile: string;
  resumes: string[];
  socialContacts: socialContacts;
  skills: string[];
  Projects: Projects[];
  phoneNumber: string;
  companiesAppliedTo: string[];
  conversationsWithHR?: conversationsWithHR[];
  id?: string; //optional because this is generated by database while storing
}

export interface socialContacts {
  linkedIn: string;
  github: string;
  mail: string;
  whatsapp: string;
}

export interface Projects {
  title: string;
  videoLink: string;
  GitHub_Repo: string;
  deployLink: string;
}

export interface conversationsWithHR {
  sender: string;
  content: string;
  timestamp: string;
}

export interface registeredHRs {
  name: string;
  email: string;
  password: string;
  id: string;
}

function LoginClientComp(): JSX.Element {
  //this below line is used to get the role/designation of the user who is trying to login.
  const searchParams = useSearchParams();
  const role = searchParams.get("role");

  //state variables in this file are local(not shared within any other component).So,Zustand is not necessary in this case.
  //when you implement proper authentication,then you need these variables through out the application . So, zustand is used in that case.
  //Basically just move these variables into global store.
  //these below two lines are used to store the email and password entered by user.
  const [email, setEmail] = useState<string>("SJCIT-HRD@gmail.com");
  const [password, setPassword] = useState<string>("123321");

  //state variables to indicate status of password visibility and credentials validity.
  const [isPasswordVisible, setIsPasswordVisible] = useState<boolean>(false);
  const [isValidAccount, setIsValidAccount] = useState<boolean>(true);

  //this is the variable which is used to navigate to HR and student interface from login page.
  const router = useRouter();

  //reset email and password fields on component mount.
  useEffect(() => {
    setEmail("");
    setPassword("");
  }, []);
  //useEffect requires explicit typing incase of custom dependency array or returning a clean-up function.

  //this function is called when user clicks on 'eye' icon/emoji.
  //this function doesnt take in any parameter and doesnt return anything.So,TS is not required
  const togglePasswordVisibility = (): void => {
    setIsPasswordVisible((prev: boolean) => !prev); //just toggles the previous state.
  };

  //this function may throw error which is handled by catch block.So,function is not directly responsible for that.
  //this function is async(means returns promise) and returns nothing(void).
  const handleSubmit = async (): Promise<void> => {
    //if email and password inputs are empty and user tries to login.
    if (!email || !password) {
      PopUpToastProvider.warning("Please fill in all fields");
      return;
    }

    try {
      //👇i think , it would be better to move this logic to a server component rather than being in a client component.
      //this is the API endpoint URL to get the credentials of HR/student.
      //based on 'role',all valid accounts are fetched.
      const response = await fetch(
        `https://hrd-database-default-rtdb.asia-southeast1.firebasedatabase.app/${role}.json`
      );

      if (!response.ok) {
        throw new Error("Network response was not ok");
      }

      //validAccounts are nothing but registeredAccounts.
      let validAccounts: registeredHRs[] | registeredStuds[]; //this can be either HRs or Students.
      validAccounts = await response.json();

      //check if there's any account with the entered credentials
      //if 'yes',then account is valid else account is invalid.
      //'find' may return undefined if there's no account with the entered credentials.
      const account: registeredHRs | registeredStuds | undefined =
        validAccounts.find(
          (validAccount: registeredHRs | registeredStuds) =>
            validAccount.email === email && validAccount.password === password
        );

      //if the account is valid.
      if (account) {
        setIsValidAccount(true); //indicating that the account is valid.
        if (role === "registeredHRs") {
          router.push("/hr/createJobPosting"); //navigate to 'create-job' page if HR logs-in successfully.
          PopUpToastProvider.success("HR Login successful");
        } else if ("USN" in account) {
          //By using 'in' operator,you explicitly tell TS to treat account as registeredStuds in this block
          //when the account is student,then TS should not check for registeredHRs 'type'.
          //TS is treating account.USN as unknown type.
          const studentUSN: string = (account as registeredStuds).USN; //So,we need to explicitly tell TS that account is registeredStuds.
          //Here store student USN in local storage.And USN is cleared when student clicks on 'logout'.

          localStorage.setItem("studentUSN", studentUSN);

          router.push("/student/studProfile"); //if student logs-in successfully,navigate to 'profile' page.
        }
      } //if the account is invalid
      else {
        setIsValidAccount(false);
        PopUpToastProvider.error("Invalid credentials.Please try again");
      }
    } catch (error) {
      console.error("Error verifying user:", error);
      PopUpToastProvider.error("Error:Unable to verify user");
    }
  };

  //❌Dont forget to write TS for this👇
  const handleForgotPassword = () => {};

  return (
    <>
      <form
        onKeyDown={(e: React.KeyboardEvent<HTMLFormElement>) => {
          if (e.key === "Enter") {
            e.preventDefault();
            handleSubmit();
          }
        }}
      >
        <div className="bg-white p-10 rounded-2xl shadow-lg flex flex-col items-center w-[400px] h-[350px]">
          <label className="text-sm mb-1 text-gray-600 w-full">Email*:</label>
          <input
            type="email"
            required
            className={`w-full p-2 border ${
              !isValidAccount
                ? "border-red-500 bg-red-100"
                : "border-gray-300 rounded-full focus:outline-none focus:ring-2 focus:ring-blue-500"
            }`}
            value={email}
            onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
              setEmail(e.target.value);
            }}
          ></input>

          <label className="text-sm mt-4 mb-1 text-gray-600 w-full">
            Password*:
          </label>
          <div className="relative w-full">
            <input
              type={isPasswordVisible ? "text" : "password"}
              required
              className={`w-full p-2 border ${
                !isValidAccount
                  ? "border-red-500 bg-red-100"
                  : "border-gray-300"
              } rounded-full focus:outline-none focus:ring-2 focus:ring-blue-500 pr-10`}
              value={password}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                setPassword(e.target.value)
              }
              style={{ paddingRight: "40px" }}
            ></input>
            <span
              onClick={(e: React.MouseEvent<HTMLSpanElement>) =>
                togglePasswordVisibility()
              }
              className="absolute right-3 top-1.5 transform-translate-y-1/2 cursor-pointer text-xl"
            >
              {isPasswordVisible ? "🙈" : "👁️"}
            </span>
            <span
              className="text-red-500 hover:text-blue-700 cursor-pointer mt-2 block"
              onClick={(e: React.MouseEvent<HTMLSpanElement>) =>
                handleForgotPassword()
              }
            >
              Forgot Password
            </span>
          </div>
          {!isValidAccount && (
            <p className="text-red-500 text-md mt-2">
              Invalid credentials.Please try again.
            </p>
          )}

          <button
            className="w-full mt-5 bg-blue-500 text-white p-3 rounded-full transition-transform hover:translate-y-[-2px] hover:bg-blue-700 shadow-md"
            onClick={(e: React.MouseEvent<HTMLButtonElement>) => {
              e.preventDefault();
              handleSubmit();
            }}
          >
            Submit
          </button>
        </div>
      </form>
    </>
  );
}

export default LoginClientComp;
