"use client";

import React, { useState, useEffect } from "react";
//useState is used to store messages[].
//useEffect is used to fetch messages from firebase.

//All 3 components:MessageContainer,MessageDisplay and MessageInput combine together to form 'messages' interface.
import MessageDisplay from "../messageDisplay/page";
import MessageInput from "../messageInput/page";

//importing for displaying 3rd party notifications.
import PopUpToastProvider from "@/app/components/PopUpToastProvider";

//TS interfaces
export interface Message {
  date: string;
  sender: string;
  text: string;
  time: string;
  readonly id?: string; //this is automatically generated by FireBase.Hence its optional
}

const MessageContainerClientComp: React.FC = () => {
  //messages are fetched from firbase.
  const [messages, setMessages] = useState<Message[]>([]);

  //Function to fetch messages from firebase
  //Promise is because of 'async' and void is because it returns nothing.
  const fetchMessages = async (): Promise<void> => {
    try {
      const response = await fetch(
        `https://hrd-database-default-rtdb.asia-southeast1.firebasedatabase.app/GroupMessages.json`,
        {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
          },
        }
      );

      if (!response.ok) {
        throw new Error(`Error fetching data:${response.status}`);
      }

      const data: Message[] = await response.json();
      const messages = data || []; //Extract messages
      setMessages(messages); //set messages in the state.
    } catch (error) {
      console.error("Error fetching messages:", error);
    }
  };

  //Function to post a new message to the firebase
  const postMessage = async (message: Message): Promise<void> => {
    try {
      //step 1:Fetch the current GroupMessages object.
      const response = await fetch(
        `https://hrd-database-default-rtdb.asia-southeast1.firebasedatabase.app/GroupMessages.json`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(message),
        }
      );

      if (!response.ok) {
        throw new Error(`Error fetching data:${response.status}`);
      }

      fetchMessages(); //calling this function,so that latest message will be displayed
      PopUpToastProvider.success("Message sent successfully!");
    } catch (error) {
      console.error("Error posting message:", error);
      PopUpToastProvider.warning(
        "There is some error while sending the message!"
      );
    }
  };

  //handle sending a message.
  const handleSendMessage = (messageText: string): void => {
    //Ensure this logic runs only on the client-side , orelse it will cause error . ex:time at the server and time at client will be slighlty different , which causes mismatch error

    if (typeof window !== "undefined") {
      //typeof window is undefined in case of server.
      //Get current date and time
      const now: Date = new Date();
      const formattedDate = now.toLocaleDateString(); //eg. "11/02/2024"
      const formattedTime = now.toLocaleTimeString([], {
        hour: "2-digit",
        minute: "2-digit",
      }); //eg. "12:45 PM"

      //create a new message object with date and time
      const newMessage: Message = {
        sender: "HR",
        text: messageText,
        date: formattedDate,
        time: formattedTime,
      };

      postMessage(newMessage); //Call postMessage function to send it to the server.
    }
  };

  //Fetch messages when the component mounts
  useEffect(() => {
    fetchMessages();
  }, []);

  return (
    <>
      <div className="flex flex-col max-w-[70%] max-h-[90%] mx-auto mt-2 p-4 bg-white rounded-lg shadow-lg overflow-y-auto breakwords">
        <MessageDisplay></MessageDisplay>
        <MessageInput
          onSend={(messageText: string) => handleSendMessage(messageText)}
        ></MessageInput>
      </div>
    </>
  );
};

export default MessageContainerClientComp;
