//This layout file is only for HR Dashboard/HR interface.

import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import HR_Navbar from "../components/HR_Navbar/HR_Navbar"; //Navbar should be displayed for entire HR interface
//this should be included so as to get toast notifications through out the project.
import { ToastRootContainer } from "../components/PopUpToastProvider";
import "../globals.css";
import LogOutComponent from "../components/LogOutComponent/LogOutComponent";
//this is used to display LogOut component when HR clicks on log-out button.

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HRLayout({
  children, //children prop cannot be modified as it is readonly.
}: Readonly<{ children: React.ReactNode }>) {
  //ReactNode means JSX element.

  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Remember ToastRootContainer should be included in all layouts */}
        <ToastRootContainer></ToastRootContainer>
        <HR_Navbar></HR_Navbar>
        <LogOutComponent></LogOutComponent>
        {children}
        <footer className="mt-auto text-center py-4 bg-blue-500 text-white text-sm">
          <p>&copy;2025 Cohort.All rights reserved</p>
        </footer>
      </body>
    </html>
  );
}
